### ISSUE TITLE
This template is slow

### ISSUE THREAD

**Issue by gambheera** [GeekyAnts/flutter-login-home-animation#5]
I downloaded this template and ran it (without any change) on Nexus 5X. But animations and UI transitions are slow. My command was 'flutter run'

And again I installed application using 'flutter install' command. But still it is slow.

Is there any special thing I have to do?

**Comment by geekruchika** [comment]
This is not our theme issue, it’s due to flutter version which causes this. Please refer this article- https://medium.com/flutter-io/https-medium-com-flutter-io-announcing-flutters-beta-2-c85ba1557d5e. As they have improved asset system in Flutter beta 2 version, mentioned in the article-“Flutter apps now launch faster as we don’t make unneeded extractions of the assets. The previous asset system occasionally caused slow launch times on older Android phones.”
